# Generated by Django 6.0.6 on 2026-06-28 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Место выполнения привычки')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время выполнения привычки')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                (
                    'periodicity',
                    models.PositiveIntegerField(default=1, verbose_name='Периодичность привычки (раз в день)'),
                ),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение')),
                ('duration', models.IntegerField(verbose_name='Время выполнения привычки (в секундах)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                (
                    'related_habit',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='habits.habit',
                        verbose_name='Связанная привычка',
                    ),
                ),
            ],
        ),
    ]
