# Generated by Django 6.0.6 on 2026-07-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_remove_habit_user_habit_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='time',
        ),
        migrations.AddField(
            model_name='habit',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время выполнения привычки'),
        ),
    ]
